Repository opendatahub-io/openvino_model_server, pull requests merged in 2024-09, with the labels that each got.

#49 Remove Depandabot from OVMS main branch
  .github/depandabot.yml
Labels: approved

#50 Update Dockerfile.redhat for 2024.3 release
  Dockerfile.redhat
Labels: lgtm, approved

#51 Fix dnf parallelism
  Dockerfile.redhat
Labels: lgtm, approved, ok-to-test
